# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetCorporationsCorporationIdBookmarksFolders200Ok(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, creator_id=None, folder_id=None, name=None):
        """
        GetCorporationsCorporationIdBookmarksFolders200Ok - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'creator_id': 'int',
            'folder_id': 'int',
            'name': 'str'
        }

        self.attribute_map = {
            'creator_id': 'creator_id',
            'folder_id': 'folder_id',
            'name': 'name'
        }

        self._creator_id = creator_id
        self._folder_id = folder_id
        self._name = name

    @property
    def creator_id(self):
        """
        Gets the creator_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        creator_id integer

        :return: The creator_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :rtype: int
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """
        Sets the creator_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        creator_id integer

        :param creator_id: The creator_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :type: int
        """

        self._creator_id = creator_id

    @property
    def folder_id(self):
        """
        Gets the folder_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        folder_id integer

        :return: The folder_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :rtype: int
        """
        return self._folder_id

    @folder_id.setter
    def folder_id(self, folder_id):
        """
        Sets the folder_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        folder_id integer

        :param folder_id: The folder_id of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :type: int
        """
        if folder_id is None:
            raise ValueError("Invalid value for `folder_id`, must not be `None`")

        self._folder_id = folder_id

    @property
    def name(self):
        """
        Gets the name of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        name string

        :return: The name of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        name string

        :param name: The name of this GetCorporationsCorporationIdBookmarksFolders200Ok.
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetCorporationsCorporationIdBookmarksFolders200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
