# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetFwLeaderboardsCharactersOk(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, kills=None, victory_points=None):
        """
        GetFwLeaderboardsCharactersOk - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'kills': 'GetFwLeaderboardsCharactersKills',
            'victory_points': 'GetFwLeaderboardsCharactersVictoryPoints'
        }

        self.attribute_map = {
            'kills': 'kills',
            'victory_points': 'victory_points'
        }

        self._kills = kills
        self._victory_points = victory_points

    @property
    def kills(self):
        """
        Gets the kills of this GetFwLeaderboardsCharactersOk.

        :return: The kills of this GetFwLeaderboardsCharactersOk.
        :rtype: GetFwLeaderboardsCharactersKills
        """
        return self._kills

    @kills.setter
    def kills(self, kills):
        """
        Sets the kills of this GetFwLeaderboardsCharactersOk.

        :param kills: The kills of this GetFwLeaderboardsCharactersOk.
        :type: GetFwLeaderboardsCharactersKills
        """

        self._kills = kills

    @property
    def victory_points(self):
        """
        Gets the victory_points of this GetFwLeaderboardsCharactersOk.

        :return: The victory_points of this GetFwLeaderboardsCharactersOk.
        :rtype: GetFwLeaderboardsCharactersVictoryPoints
        """
        return self._victory_points

    @victory_points.setter
    def victory_points(self, victory_points):
        """
        Sets the victory_points of this GetFwLeaderboardsCharactersOk.

        :param victory_points: The victory_points of this GetFwLeaderboardsCharactersOk.
        :type: GetFwLeaderboardsCharactersVictoryPoints
        """

        self._victory_points = victory_points

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetFwLeaderboardsCharactersOk):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
