# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class GetCharactersCharacterIdNotificationsContacts200Ok(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, message=None, notification_id=None, send_date=None, sender_character_id=None, standing_level=None):
        """
        GetCharactersCharacterIdNotificationsContacts200Ok - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'message': 'str',
            'notification_id': 'int',
            'send_date': 'datetime',
            'sender_character_id': 'int',
            'standing_level': 'float'
        }

        self.attribute_map = {
            'message': 'message',
            'notification_id': 'notification_id',
            'send_date': 'send_date',
            'sender_character_id': 'sender_character_id',
            'standing_level': 'standing_level'
        }

        self._message = message
        self._notification_id = notification_id
        self._send_date = send_date
        self._sender_character_id = sender_character_id
        self._standing_level = standing_level

    @property
    def message(self):
        """
        Gets the message of this GetCharactersCharacterIdNotificationsContacts200Ok.
        message string

        :return: The message of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this GetCharactersCharacterIdNotificationsContacts200Ok.
        message string

        :param message: The message of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")

        self._message = message

    @property
    def notification_id(self):
        """
        Gets the notification_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        notification_id integer

        :return: The notification_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :rtype: int
        """
        return self._notification_id

    @notification_id.setter
    def notification_id(self, notification_id):
        """
        Sets the notification_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        notification_id integer

        :param notification_id: The notification_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :type: int
        """
        if notification_id is None:
            raise ValueError("Invalid value for `notification_id`, must not be `None`")

        self._notification_id = notification_id

    @property
    def send_date(self):
        """
        Gets the send_date of this GetCharactersCharacterIdNotificationsContacts200Ok.
        send_date string

        :return: The send_date of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :rtype: datetime
        """
        return self._send_date

    @send_date.setter
    def send_date(self, send_date):
        """
        Sets the send_date of this GetCharactersCharacterIdNotificationsContacts200Ok.
        send_date string

        :param send_date: The send_date of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :type: datetime
        """
        if send_date is None:
            raise ValueError("Invalid value for `send_date`, must not be `None`")

        self._send_date = send_date

    @property
    def sender_character_id(self):
        """
        Gets the sender_character_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        sender_character_id integer

        :return: The sender_character_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :rtype: int
        """
        return self._sender_character_id

    @sender_character_id.setter
    def sender_character_id(self, sender_character_id):
        """
        Sets the sender_character_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        sender_character_id integer

        :param sender_character_id: The sender_character_id of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :type: int
        """
        if sender_character_id is None:
            raise ValueError("Invalid value for `sender_character_id`, must not be `None`")

        self._sender_character_id = sender_character_id

    @property
    def standing_level(self):
        """
        Gets the standing_level of this GetCharactersCharacterIdNotificationsContacts200Ok.
        A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent

        :return: The standing_level of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :rtype: float
        """
        return self._standing_level

    @standing_level.setter
    def standing_level(self, standing_level):
        """
        Sets the standing_level of this GetCharactersCharacterIdNotificationsContacts200Ok.
        A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent

        :param standing_level: The standing_level of this GetCharactersCharacterIdNotificationsContacts200Ok.
        :type: float
        """
        if standing_level is None:
            raise ValueError("Invalid value for `standing_level`, must not be `None`")

        self._standing_level = standing_level

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, GetCharactersCharacterIdNotificationsContacts200Ok):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
