# coding: utf-8

"""
    EVE Swagger Interface

    An OpenAPI for EVE Online

    OpenAPI spec version: 0.6.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PutCharactersCharacterIdCalendarEventIdResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, response=None):
        """
        PutCharactersCharacterIdCalendarEventIdResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'response': 'str'
        }

        self.attribute_map = {
            'response': 'response'
        }

        self._response = response

    @property
    def response(self):
        """
        Gets the response of this PutCharactersCharacterIdCalendarEventIdResponse.
        response string

        :return: The response of this PutCharactersCharacterIdCalendarEventIdResponse.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response):
        """
        Sets the response of this PutCharactersCharacterIdCalendarEventIdResponse.
        response string

        :param response: The response of this PutCharactersCharacterIdCalendarEventIdResponse.
        :type: str
        """
        allowed_values = ["accepted", "declined", "tentative"]
        if response not in allowed_values:
            raise ValueError(
                "Invalid value for `response` ({0}), must be one of {1}"
                .format(response, allowed_values)
            )

        self._response = response

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PutCharactersCharacterIdCalendarEventIdResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
