# use with: logging.config.dictConfig(yaml.load(open('logging.yaml', 'r')))

# Formatters detailed here: http://docs.python.org/2/library/logging.html#logrecord-attributes

# levels: INFO, DEBUG, WARNING

version: 1
formatters:
  console:
    format: '[%(asctime)s][%(name)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detail:
    format: '[%(asctime)s][%(levelname)s][File: %(filename)s][%(funcName)s()][Line: %(lineno)d]: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

loggers:
  discord:
    handlers: [discord]
    propagate: false
    qualname: discord
    level: INFO
  discord.http:
    handlers: [discord_http]
    propagate: false
    qualname: discord.http
    level: INFO
  library:
    handlers: [library, console]
    propagate: false  # We dont want this logs going everywhere
    qualname: library
    level: INFO
  modules:
    handlers: [module]
    propagate: false
    qualname: modules.*
    level: INFO

handlers:
  console:
    class: logging.StreamHandler
    #level: INFO
    formatter: console
    stream: ext://sys.stdout
  all:
    class: logging.handlers.RotatingFileHandler
    #level: DEBUG
    formatter: simple
    encoding: utf-8
    mode: a
    backupCount: 3
    filename: logs/broadsword.log
  library:
    class: logging.handlers.RotatingFileHandler
    #level: DEBUG
    formatter: simple
    encoding: utf-8
    mode: a
    maxBytes: 1048576
    backupCount: 3
    filename: logs/library.log
  module:
    class: logging.handlers.RotatingFileHandler
    #level: DEBUG
    formatter: simple
    encoding: utf-8
    mode: a
    maxBytes: 1048576
    backupCount: 3
    filename: logs/module.log
  discord:
    class: logging.handlers.RotatingFileHandler
    #level: INFO
    formatter: simple
    encoding: utf-8
    mode: a
    maxBytes: 1048576
    backupCount: 3
    filename: logs/discord.log
  discord_http:
    class: logging.handlers.RotatingFileHandler
    #level: WARNING
    formatter: simple
    encoding: utf-8
    mode: a
    maxBytes: 1048576
    backupCount: 3
    filename: logs/discord-http.log

root:
  level: INFO
  handlers: [console, all]
  propagate: true